=== plataforma-educativa/batalla-espacial-svn/trunk/batalla-espacial/src/test/resources/ar/com/comunidadesfera/eficiencia/test/persistencia/consultas/dataset.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:dflt="EFICIENCIA">
	<xsd:import namespace="EFICIENCIA" schemaLocation="EFICIENCIA.xsd" />
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="PROBLEMA" type="dflt:PROBLEMA__type" />
				<xsd:element name="MODULO" type="dflt:MODULO__type" />
				<xsd:element name="DIMENSION" type="dflt:DIMENSION__type" />
				<xsd:element name="REGISTRODEEJECUCION" type="dflt:REGISTRODEEJECUCION__type" />
				<xsd:element name="CATEGORIA" type="dflt:CATEGORIA__type" />
				<xsd:element name="MEDIDA" type="dflt:MEDIDA__type" />
				<xsd:element name="MEDICION" type="dflt:MEDICION__type" />
				<xsd:element name="DISCRIMINANTE" type="dflt:DISCRIMINANTE__type" />
				<xsd:any namespace="EFICIENCIA" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== plataforma-educativa/batalla-espacial-svn/batalla-espacial/src/test/resources/ar/com/comunidadesfera/eficiencia/test/persistencia/consultas/SumarizarMedicionesPorDiscriminanteDimensionEnUnEntornoTest.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dataset.xsd">

    <PROBLEMA ID="1" NOMBRE="Ordenar"/>
    
    <DISCRIMINANTE ID="1" NOMBRE="OrdenamientoNulo"/>
    <MODULO ID="1" IDENTIFICACION="OrdenamientoNulo" VERSION="1"/>
    
    <!--           -->
    <!-- Seleccion -->
    <!--           -->
    <DISCRIMINANTE ID="2" NOMBRE="OrdenamientoPorSeleccion"/>
    <MODULO ID="2" IDENTIFICACION="OrdenamientoPorSeleccion" VERSION="1"/>

    <DISCRIMINANTE ID="3" NOMBRE="Comparaciones" ENTORNO_ID="2"/>
    <CATEGORIA ID="3" MODULO_ID="2"/>

    <DISCRIMINANTE ID="4" NOMBRE="Intercambios" ENTORNO_ID="2"/>
    <CATEGORIA ID="4" MODULO_ID="2"/>
    
    <!-- 1er Registro -->
    <REGISTRODEEJECUCION ID="1" PROBLEMA_ID="1" MODULO_ID="2" DIMENSION="10" INICIO="2013-04-22 11:23:33.000000001" FIN="2013-04-22 11:23:33.000000054"/>
    <MEDIDA ID="1" MAGNITUD="100" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="1" DISCRIMINANTE_ID="2" EJECUCION_ID="1" RESULTADO_ID="1"/>
    
    <MEDIDA ID="2" MAGNITUD="91" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="2" DISCRIMINANTE_ID="3" EJECUCION_ID="1" RESULTADO_ID="2"/>
    
    <MEDIDA ID="3" MAGNITUD="9" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="3" DISCRIMINANTE_ID="4" EJECUCION_ID="1" RESULTADO_ID="3"/>

    <!-- 2do Registro -->
    <REGISTRODEEJECUCION ID="2" PROBLEMA_ID="1" MODULO_ID="2" DIMENSION="20" INICIO="2013-04-22 12:23:33.000000001" FIN="2013-04-22 12:23:33.000000054"/>
    <MEDIDA ID="4" MAGNITUD="400" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="4" DISCRIMINANTE_ID="2" EJECUCION_ID="2" RESULTADO_ID="4"/>
    
    <MEDIDA ID="5" MAGNITUD="381" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="5" DISCRIMINANTE_ID="3" EJECUCION_ID="2" RESULTADO_ID="5"/>
    
    <MEDIDA ID="6" MAGNITUD="19" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="6" DISCRIMINANTE_ID="4" EJECUCION_ID="2" RESULTADO_ID="6"/>
    
    <!-- 3do Registro -->
    <REGISTRODEEJECUCION ID="3" PROBLEMA_ID="1" MODULO_ID="2" DIMENSION="20" INICIO="2013-04-22 12:25:33.000000001" FIN="2013-04-22 12:26:33.000000054"/>
    <MEDIDA ID="7" MAGNITUD="408" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="7" DISCRIMINANTE_ID="2" EJECUCION_ID="2" RESULTADO_ID="7"/>
    
    <MEDIDA ID="8" MAGNITUD="387" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="8" DISCRIMINANTE_ID="3" EJECUCION_ID="3" RESULTADO_ID="8"/>
    
    <MEDIDA ID="9" MAGNITUD="21" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="9" DISCRIMINANTE_ID="4" EJECUCION_ID="3" RESULTADO_ID="9"/>
    
</dataset>

=== plataforma-educativa/batalla-espacial-svn/branches/2.0.x/batalla-espacial/src/test/resources/ar/com/comunidadesfera/eficiencia/test/persistencia/consultas/SumarizarMedicionesPorDiscriminanteEnUnEntornoTest.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dataset.xsd">

    <PROBLEMA ID="1" NOMBRE="Ordenar"/>
    
    <DISCRIMINANTE ID="1" NOMBRE="OrdenamientoNulo"/>
    <MODULO ID="1" IDENTIFICACION="OrdenamientoNulo" VERSION="1"/>

    <!--           -->
    <!-- Seleccion -->
    <!--           -->
    <DISCRIMINANTE ID="2" NOMBRE="OrdenamientoPorSeleccion"/>
    <MODULO ID="2" IDENTIFICACION="OrdenamientoPorSeleccion" VERSION="1"/>

    <DISCRIMINANTE ID="3" NOMBRE="Comparaciones" ENTORNO_ID="2"/>
    <CATEGORIA ID="3" MODULO_ID="2"/>

    <DISCRIMINANTE ID="4" NOMBRE="Intercambios" ENTORNO_ID="2"/>
    <CATEGORIA ID="4" MODULO_ID="2"/>
    
    <!-- 1er Registro -->
    <REGISTRODEEJECUCION ID="1" PROBLEMA_ID="1" MODULO_ID="2" DIMENSION="10" INICIO="2013-04-22 11:23:33.000000001" FIN="2013-04-22 11:23:33.000000054"/>
    <MEDIDA ID="1" MAGNITUD="100" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="1" DISCRIMINANTE_ID="2" EJECUCION_ID="1" RESULTADO_ID="1"/>
    
    <MEDIDA ID="2" MAGNITUD="91" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="2" DISCRIMINANTE_ID="3" EJECUCION_ID="1" RESULTADO_ID="2"/>
    
    <MEDIDA ID="3" MAGNITUD="9" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="3" DISCRIMINANTE_ID="4" EJECUCION_ID="1" RESULTADO_ID="3"/>

    <!-- 2do Registro -->
    <REGISTRODEEJECUCION ID="2" PROBLEMA_ID="1" MODULO_ID="2" DIMENSION="20" INICIO="2013-04-22 12:23:33.000000001" FIN="2013-04-22 12:23:33.000000054"/>
    <MEDIDA ID="4" MAGNITUD="400" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="4" DISCRIMINANTE_ID="2" EJECUCION_ID="2" RESULTADO_ID="4"/>
    
    <MEDIDA ID="5" MAGNITUD="381" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="5" DISCRIMINANTE_ID="3" EJECUCION_ID="2" RESULTADO_ID="5"/>
    
    <MEDIDA ID="6" MAGNITUD="19" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="6" DISCRIMINANTE_ID="4" EJECUCION_ID="2" RESULTADO_ID="6"/>

    <!--           -->
    <!-- Insercion -->
    <!--           -->
    <DISCRIMINANTE ID="5" NOMBRE="OrdenamientoPorInsercion"/>
    <MODULO ID="5" IDENTIFICACION="OrdenamientoPorInsercion" VERSION="3"/>
    
    <DISCRIMINANTE ID="6" NOMBRE="Intercambios" ENTORNO_ID="5"/>
    <CATEGORIA ID="6" MODULO_ID="5"/>
    
    <DISCRIMINANTE ID="7" NOMBRE="Comparaciones" ENTORNO_ID="5"/>
    <CATEGORIA ID="7" MODULO_ID="5"/>
    
    <DISCRIMINANTE ID="8" NOMBRE="Errores" ENTORNO_ID="5"/>
    <CATEGORIA ID="8" MODULO_ID="5"/>

    <!-- 1er Registro -->
    <REGISTRODEEJECUCION ID="3" PROBLEMA_ID="1" MODULO_ID="5" DIMENSION="2" INICIO="2012-05-12 15:12:45.000042369" FIN="2012-05-12 15:13:03.000041125"/>
    <MEDIDA ID="7" MAGNITUD="3" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="7" DISCRIMINANTE_ID="5" EJECUCION_ID="3" RESULTADO_ID="7"/>
    
    <MEDIDA ID="8" MAGNITUD="1" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="8" DISCRIMINANTE_ID="6" EJECUCION_ID="3" RESULTADO_ID="8"/>

    <MEDIDA ID="9" MAGNITUD="2" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="9" DISCRIMINANTE_ID="7" EJECUCION_ID="3" RESULTADO_ID="9"/>
    
    <!-- 2do Registro -->
    <REGISTRODEEJECUCION ID="4" PROBLEMA_ID="1" MODULO_ID="5" DIMENSION="3" INICIO="2012-05-12 15:13:45.000042369" FIN="2012-05-12 15:14:03.000041125"/>
    <MEDIDA ID="10" MAGNITUD="8" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="10" DISCRIMINANTE_ID="5" EJECUCION_ID="4" RESULTADO_ID="10"/>
    
    <MEDIDA ID="11" MAGNITUD="3" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="11" DISCRIMINANTE_ID="6" EJECUCION_ID="4" RESULTADO_ID="11"/>

    <MEDIDA ID="12" MAGNITUD="5" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="12" DISCRIMINANTE_ID="7" EJECUCION_ID="4" RESULTADO_ID="12"/>
    
    <!-- 3er Registro -->
    <REGISTRODEEJECUCION ID="5" PROBLEMA_ID="1" MODULO_ID="5" DIMENSION="4" INICIO="2012-05-12 15:14:45.000042369" FIN="2012-05-12 15:15:03.000041125"/>
    <MEDIDA ID="13" MAGNITUD="16" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="13" DISCRIMINANTE_ID="5" EJECUCION_ID="5" RESULTADO_ID="13"/>
    
    <MEDIDA ID="14" MAGNITUD="5" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="14" DISCRIMINANTE_ID="6" EJECUCION_ID="5" RESULTADO_ID="14"/>

    <MEDIDA ID="15" MAGNITUD="11" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="15" DISCRIMINANTE_ID="7" EJECUCION_ID="5" RESULTADO_ID="15"/>
        
    <!-- 4to Registro -->
    <REGISTRODEEJECUCION ID="6" PROBLEMA_ID="1" MODULO_ID="5" DIMENSION="5" INICIO="2012-05-12 15:15:45.000042369" FIN="2012-05-12 15:16:03.000041125"/>
    <MEDIDA ID="16" MAGNITUD="23" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="16" DISCRIMINANTE_ID="5" EJECUCION_ID="6" RESULTADO_ID="16"/>
    
    <MEDIDA ID="17" MAGNITUD="8" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="17" DISCRIMINANTE_ID="6" EJECUCION_ID="6" RESULTADO_ID="17"/>

    <MEDIDA ID="18" MAGNITUD="15" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="18" DISCRIMINANTE_ID="7" EJECUCION_ID="6" RESULTADO_ID="18"/>
    
    <!-- 5to Registro -->
    <REGISTRODEEJECUCION ID="7" PROBLEMA_ID="1" MODULO_ID="5" DIMENSION="6" INICIO="2012-05-12 15:16:45.000042369" FIN="2012-05-12 15:17:03.000041125"/>
    <MEDIDA ID="19" MAGNITUD="36" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="19" DISCRIMINANTE_ID="5" EJECUCION_ID="7" RESULTADO_ID="19"/>
    
    <MEDIDA ID="20" MAGNITUD="12" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="20" DISCRIMINANTE_ID="6" EJECUCION_ID="7" RESULTADO_ID="20"/>

    <MEDIDA ID="21" MAGNITUD="24" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="21" DISCRIMINANTE_ID="7" EJECUCION_ID="7" RESULTADO_ID="21"/>
    
    <!-- 6to Registro: La dimension es 2 y estaba ordenado solo tiene un registro en la categoria Comparacion y ninguno en Intercambio -->
    <REGISTRODEEJECUCION ID="8" PROBLEMA_ID="1" MODULO_ID="5" DIMENSION="2" INICIO="2012-05-12 15:17:45.000042369" FIN="2012-05-12 15:18:03.000041125"/>
    <MEDIDA ID="22" MAGNITUD="1" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="22" DISCRIMINANTE_ID="5" EJECUCION_ID="8" RESULTADO_ID="22"/>
    
    <MEDIDA ID="23" MAGNITUD="1" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="23" DISCRIMINANTE_ID="7" EJECUCION_ID="8" RESULTADO_ID="23"/>

    <!-- 7mo Registro: La dimension es 0 tiene un registro en la categoria Error -->
    <REGISTRODEEJECUCION ID="9" PROBLEMA_ID="1" MODULO_ID="5" DIMENSION="0" INICIO="2012-05-12 15:17:45.000042369" FIN="2012-05-12 15:18:03.000041125"/>
    <MEDIDA ID="24" MAGNITUD="1" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="24" DISCRIMINANTE_ID="5" EJECUCION_ID="9" RESULTADO_ID="24"/>
    
    <MEDIDA ID="25" MAGNITUD="1" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="25" DISCRIMINANTE_ID="8" EJECUCION_ID="9" RESULTADO_ID="25"/>

    <!-- 8vo Registro: La dimension es 1, el computo total de operaciones es 0, no tiene registro en ninguna categoria -->
    <REGISTRODEEJECUCION ID="10" PROBLEMA_ID="1" MODULO_ID="5" DIMENSION="1" INICIO="2012-05-12 15:17:45.000042369" FIN="2012-05-12 15:18:03.000041125"/>
    <MEDIDA ID="26" MAGNITUD="0" UNIDAD="INSTRUCCIONES" />
    <MEDICION ID="26" DISCRIMINANTE_ID="5" EJECUCION_ID="10" RESULTADO_ID="26"/>
  
    <!--                  -->  
    <!-- Trasponer Matriz -->
    <!--                  -->  
    <PROBLEMA ID="2" NOMBRE="TransponerMatriz"/>
    
    <DISCRIMINANTE ID="9" NOMBRE="TrasponerCopiando"/>
    <MODULO ID="9" IDENTIFICACION="TrasponerCopiando" VERSION="3"/>
    
    <DISCRIMINANTE ID="10" NOMBRE="Intercambios" ENTORNO_ID="9"/>
    <CATEGORIA ID="10" MODULO_ID="9"/>
    
    <DISCRIMINANTE ID="11" NOMBRE="Validaciones" ENTORNO_ID="9"/>
    <CATEGORIA ID="11" MODULO_ID="9"/>
    
    <DISCRIMINANTE ID="12" NOMBRE="MatrizTemporal" ENTORNO_ID="9"/>
    <CATEGORIA ID="12" MODULO_ID="9"/>
    
    <!-- 1er Registro -->
    <REGISTRODEEJECUCION ID="11" PROBLEMA_ID="2" MODULO_ID="9" DIMENSION="10" INICIO="2012-06-15 08:23:22.000054785" FIN="2012-06-15 08:23:45.000087421"/>
    <MEDIDA ID="27" MAGNITUD="110" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="27" DISCRIMINANTE_ID="9" EJECUCION_ID="11" RESULTADO_ID="27"/>
    <MEDIDA ID="28" MAGNITUD="400" UNIDAD="BYTES"/>
    <MEDICION ID="28" DISCRIMINANTE_ID="9" EJECUCION_ID="11" RESULTADO_ID="28"/>
    
    <MEDIDA ID="29" MAGNITUD="100" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="29" DISCRIMINANTE_ID="10" EJECUCION_ID="11" RESULTADO_ID="29"/>
    <MEDIDA ID="30" MAGNITUD="10" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="30" DISCRIMINANTE_ID="11" EJECUCION_ID="11" RESULTADO_ID="30"/>
    <MEDIDA ID="31" MAGNITUD="400" UNIDAD="BYTES"/>
    <MEDICION ID="31" DISCRIMINANTE_ID="12" EJECUCION_ID="11" RESULTADO_ID="31"/>
    
    <!-- 2do Registro -->
    <REGISTRODEEJECUCION ID="12" PROBLEMA_ID="2" MODULO_ID="9" DIMENSION="100" INICIO="2012-06-15 08:28:22.000054785" FIN="2012-06-15 08:29:22.000054785"/>
    <MEDIDA ID="32" MAGNITUD="100100" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="32" DISCRIMINANTE_ID="9" EJECUCION_ID="12" RESULTADO_ID="32"/>
    <MEDIDA ID="33" MAGNITUD="40000" UNIDAD="BYTES"/>
    <MEDICION ID="33" DISCRIMINANTE_ID="9" EJECUCION_ID="12" RESULTADO_ID="33"/>
    
    <MEDIDA ID="34" MAGNITUD="100000" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="34" DISCRIMINANTE_ID="10" EJECUCION_ID="12" RESULTADO_ID="34"/>
    <MEDIDA ID="35" MAGNITUD="100" UNIDAD="INSTRUCCIONES"/>
    <MEDICION ID="35" DISCRIMINANTE_ID="11" EJECUCION_ID="12" RESULTADO_ID="35"/>
    <MEDIDA ID="36" MAGNITUD="40000" UNIDAD="BYTES"/>
    <MEDICION ID="36" DISCRIMINANTE_ID="12" EJECUCION_ID="12" RESULTADO_ID="36"/>
    
    
</dataset>

=== plataforma-educativa/batalla-espacial-svn/batalla-espacial/src/test/resources/ar/com/comunidadesfera/eficiencia/test/persistencia/consultas/CalcularMedicionesDeUnModuloTest.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dataset.xsd">

    <DISCRIMINANTE ID="1" NOMBRE="BusquedaSecuencial"/>
    <MODULO ID="1" IDENTIFICACION="BusquedaSecuencial" VERSION="1"/>

    <DISCRIMINANTE ID="2" NOMBRE="BusquedaBinaria"/>
    <MODULO ID="2" IDENTIFICACION="BusquedaBinaria" VERSION="1"/>
    
    <DISCRIMINANTE ID="3" NOMBRE="OrdenamientoPorSeleccion"/>
    <MODULO ID="3" IDENTIFICACION="OrdenamientoPorSeleccion" VERSION="2"/>
    
    <PROBLEMA ID="1" NOMBRE="Buscar"/>

    <MEDIDA ID="100" MAGNITUD="276" UNIDAD="INSTRUCCIONES"/>
    <REGISTRODEEJECUCION ID="10" PROBLEMA_ID="1" MODULO_ID="2" DIMENSION="1000" INICIO="2013-04-22 11:23:33.000000001" FIN="2013-04-22 11:23:33.000000054"/>
    <MEDICION ID="100" DISCRIMINANTE_ID="2" EJECUCION_ID="10" RESULTADO_ID="100"/>
     
    <PROBLEMA ID="2" NOMBRE="Ordenar"/>
    
    <MEDIDA ID="201" MAGNITUD="1002" UNIDAD="INSTRUCCIONES"/>
    <REGISTRODEEJECUCION ID="21" PROBLEMA_ID="2" MODULO_ID="3" DIMENSION="10" INICIO="2013-11-05 13:21:23.000000001" FIN="2013-11-05 13:22:38.000000154"/> 
    <MEDICION ID="201" DISCRIMINANTE_ID="3" EJECUCION_ID="21" RESULTADO_ID="201"/>     

    <MEDIDA ID="202" MAGNITUD="4102" UNIDAD="INSTRUCCIONES"/>
    <REGISTRODEEJECUCION ID="22" PROBLEMA_ID="2" MODULO_ID="3" DIMENSION="20" INICIO="2013-11-05 14:21:23.000000001" FIN="2013-11-05 14:22:38.000000154"/> 
    <MEDICION ID="202" DISCRIMINANTE_ID="3" EJECUCION_ID="22" RESULTADO_ID="202"/>     

    <MEDIDA ID="203" MAGNITUD="2005" UNIDAD="INSTRUCCIONES"/>
    <REGISTRODEEJECUCION ID="23" PROBLEMA_ID="2" MODULO_ID="3" DIMENSION="15" INICIO="2013-11-05 14:25:58.000000754" FIN="2013-11-05 14:29:08.000000879"/> 
    <MEDICION ID="203" DISCRIMINANTE_ID="3" EJECUCION_ID="23" RESULTADO_ID="203"/>     

</dataset>
